/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ComplianceRegistry {
  export type AuditEntryStruct = {
    subject: AddressLike;
    action: string;
    performer: AddressLike;
    timestamp: BigNumberish;
    details: string;
  };

  export type AuditEntryStructOutput = [
    subject: string,
    action: string,
    performer: string,
    timestamp: bigint,
    details: string
  ] & {
    subject: string;
    action: string;
    performer: string;
    timestamp: bigint;
    details: string;
  };
}

export interface ComplianceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLIANCE_OFFICER"
      | "DEFAULT_ADMIN_ROLE"
      | "addRule"
      | "auditLog"
      | "batchSetSanctions"
      | "getAuditEntries"
      | "getAuditLogLength"
      | "getRoleAdmin"
      | "getRuleCount"
      | "grantRole"
      | "hasRole"
      | "identities"
      | "isApprovedForToken"
      | "isCompliant"
      | "renounceRole"
      | "revokeRole"
      | "ruleIndex"
      | "rules"
      | "sanctionsList"
      | "setIdentity"
      | "setSanction"
      | "setTokenApproval"
      | "supportsInterface"
      | "toggleRule"
      | "tokenApprovals"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditLogged"
      | "ComplianceRuleAdded"
      | "ComplianceRuleToggled"
      | "IdentityUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SanctionUpdated"
      | "TokenApprovalSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLIANCE_OFFICER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRule",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "auditLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetSanctions",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditEntries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditLogLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRuleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForToken",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCompliant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "ruleIndex", values: [string]): string;
  encodeFunctionData(functionFragment: "rules", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "sanctionsList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdentity",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setSanction",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenApproval",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "toggleRule", values: [string]): string;
  encodeFunctionData(
    functionFragment: "tokenApprovals",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLIANCE_OFFICER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "auditLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSetSanctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditLogLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRuleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "identities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCompliant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ruleIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sanctionsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSanction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "toggleRule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenApprovals",
    data: BytesLike
  ): Result;
}

export namespace AuditLoggedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    subject: AddressLike,
    action: string
  ];
  export type OutputTuple = [entryId: bigint, subject: string, action: string];
  export interface OutputObject {
    entryId: bigint;
    subject: string;
    action: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceRuleAddedEvent {
  export type InputTuple = [
    ruleId: string,
    description: string,
    jurisdiction: string
  ];
  export type OutputTuple = [
    ruleId: string,
    description: string,
    jurisdiction: string
  ];
  export interface OutputObject {
    ruleId: string;
    description: string;
    jurisdiction: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceRuleToggledEvent {
  export type InputTuple = [ruleId: string, active: boolean];
  export type OutputTuple = [ruleId: string, active: boolean];
  export interface OutputObject {
    ruleId: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityUpdatedEvent {
  export type InputTuple = [
    account: AddressLike,
    status: BigNumberish,
    investorType: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    status: bigint,
    investorType: bigint
  ];
  export interface OutputObject {
    account: string;
    status: bigint;
    investorType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SanctionUpdatedEvent {
  export type InputTuple = [account: AddressLike, sanctioned: boolean];
  export type OutputTuple = [account: string, sanctioned: boolean];
  export interface OutputObject {
    account: string;
    sanctioned: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenApprovalSetEvent {
  export type InputTuple = [
    investor: AddressLike,
    token: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    investor: string,
    token: string,
    approved: boolean
  ];
  export interface OutputObject {
    investor: string;
    token: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceRegistry;
  waitForDeployment(): Promise<this>;

  interface: ComplianceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLIANCE_OFFICER: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  addRule: TypedContractMethod<
    [ruleId_: string, description_: string, jurisdiction_: string],
    [void],
    "nonpayable"
  >;

  auditLog: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string] & {
        subject: string;
        action: string;
        performer: string;
        timestamp: bigint;
        details: string;
      }
    ],
    "view"
  >;

  batchSetSanctions: TypedContractMethod<
    [accounts: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;

  getAuditEntries: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [ComplianceRegistry.AuditEntryStructOutput[]],
    "view"
  >;

  getAuditLogLength: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRuleCount: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  identities: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        kycStatus: bigint;
        investorType: bigint;
        jurisdiction: string;
        kycDocHash: string;
        verifiedAt: bigint;
        expiresAt: bigint;
        sanctioned: boolean;
        pep: boolean;
        riskScore: bigint;
      }
    ],
    "view"
  >;

  isApprovedForToken: TypedContractMethod<
    [investor: AddressLike, token: AddressLike],
    [boolean],
    "view"
  >;

  isCompliant: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  ruleIndex: TypedContractMethod<[arg0: string], [bigint], "view">;

  rules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, string, bigint] & {
        ruleId: string;
        description: string;
        active: boolean;
        jurisdiction: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  sanctionsList: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setIdentity: TypedContractMethod<
    [
      account: AddressLike,
      status: BigNumberish,
      investorType_: BigNumberish,
      jurisdiction_: string,
      kycDocHash_: string,
      expiresAt_: BigNumberish,
      pep_: boolean,
      riskScore_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setSanction: TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setTokenApproval: TypedContractMethod<
    [investor: AddressLike, token: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  toggleRule: TypedContractMethod<[ruleId_: string], [void], "nonpayable">;

  tokenApprovals: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLIANCE_OFFICER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addRule"
  ): TypedContractMethod<
    [ruleId_: string, description_: string, jurisdiction_: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "auditLog"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string] & {
        subject: string;
        action: string;
        performer: string;
        timestamp: bigint;
        details: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchSetSanctions"
  ): TypedContractMethod<
    [accounts: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuditEntries"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [ComplianceRegistry.AuditEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuditLogLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRuleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identities"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        kycStatus: bigint;
        investorType: bigint;
        jurisdiction: string;
        kycDocHash: string;
        verifiedAt: bigint;
        expiresAt: bigint;
        sanctioned: boolean;
        pep: boolean;
        riskScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForToken"
  ): TypedContractMethod<
    [investor: AddressLike, token: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCompliant"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ruleIndex"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "rules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, string, bigint] & {
        ruleId: string;
        description: string;
        active: boolean;
        jurisdiction: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sanctionsList"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setIdentity"
  ): TypedContractMethod<
    [
      account: AddressLike,
      status: BigNumberish,
      investorType_: BigNumberish,
      jurisdiction_: string,
      kycDocHash_: string,
      expiresAt_: BigNumberish,
      pep_: boolean,
      riskScore_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSanction"
  ): TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenApproval"
  ): TypedContractMethod<
    [investor: AddressLike, token: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "toggleRule"
  ): TypedContractMethod<[ruleId_: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenApprovals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AuditLogged"
  ): TypedContractEvent<
    AuditLoggedEvent.InputTuple,
    AuditLoggedEvent.OutputTuple,
    AuditLoggedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceRuleAdded"
  ): TypedContractEvent<
    ComplianceRuleAddedEvent.InputTuple,
    ComplianceRuleAddedEvent.OutputTuple,
    ComplianceRuleAddedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceRuleToggled"
  ): TypedContractEvent<
    ComplianceRuleToggledEvent.InputTuple,
    ComplianceRuleToggledEvent.OutputTuple,
    ComplianceRuleToggledEvent.OutputObject
  >;
  getEvent(
    key: "IdentityUpdated"
  ): TypedContractEvent<
    IdentityUpdatedEvent.InputTuple,
    IdentityUpdatedEvent.OutputTuple,
    IdentityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SanctionUpdated"
  ): TypedContractEvent<
    SanctionUpdatedEvent.InputTuple,
    SanctionUpdatedEvent.OutputTuple,
    SanctionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenApprovalSet"
  ): TypedContractEvent<
    TokenApprovalSetEvent.InputTuple,
    TokenApprovalSetEvent.OutputTuple,
    TokenApprovalSetEvent.OutputObject
  >;

  filters: {
    "AuditLogged(uint256,address,string)": TypedContractEvent<
      AuditLoggedEvent.InputTuple,
      AuditLoggedEvent.OutputTuple,
      AuditLoggedEvent.OutputObject
    >;
    AuditLogged: TypedContractEvent<
      AuditLoggedEvent.InputTuple,
      AuditLoggedEvent.OutputTuple,
      AuditLoggedEvent.OutputObject
    >;

    "ComplianceRuleAdded(string,string,string)": TypedContractEvent<
      ComplianceRuleAddedEvent.InputTuple,
      ComplianceRuleAddedEvent.OutputTuple,
      ComplianceRuleAddedEvent.OutputObject
    >;
    ComplianceRuleAdded: TypedContractEvent<
      ComplianceRuleAddedEvent.InputTuple,
      ComplianceRuleAddedEvent.OutputTuple,
      ComplianceRuleAddedEvent.OutputObject
    >;

    "ComplianceRuleToggled(string,bool)": TypedContractEvent<
      ComplianceRuleToggledEvent.InputTuple,
      ComplianceRuleToggledEvent.OutputTuple,
      ComplianceRuleToggledEvent.OutputObject
    >;
    ComplianceRuleToggled: TypedContractEvent<
      ComplianceRuleToggledEvent.InputTuple,
      ComplianceRuleToggledEvent.OutputTuple,
      ComplianceRuleToggledEvent.OutputObject
    >;

    "IdentityUpdated(address,uint8,uint8)": TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
    IdentityUpdated: TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SanctionUpdated(address,bool)": TypedContractEvent<
      SanctionUpdatedEvent.InputTuple,
      SanctionUpdatedEvent.OutputTuple,
      SanctionUpdatedEvent.OutputObject
    >;
    SanctionUpdated: TypedContractEvent<
      SanctionUpdatedEvent.InputTuple,
      SanctionUpdatedEvent.OutputTuple,
      SanctionUpdatedEvent.OutputObject
    >;

    "TokenApprovalSet(address,address,bool)": TypedContractEvent<
      TokenApprovalSetEvent.InputTuple,
      TokenApprovalSetEvent.OutputTuple,
      TokenApprovalSetEvent.OutputObject
    >;
    TokenApprovalSet: TypedContractEvent<
      TokenApprovalSetEvent.InputTuple,
      TokenApprovalSetEvent.OutputTuple,
      TokenApprovalSetEvent.OutputObject
    >;
  };
}
