/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TreasuryVault {
  export type RebalanceActionStruct = {
    fromToken: AddressLike;
    toToken: AddressLike;
    amount: BigNumberish;
    executor: AddressLike;
    timestamp: BigNumberish;
  };

  export type RebalanceActionStructOutput = [
    fromToken: string,
    toToken: string,
    amount: bigint,
    executor: string,
    timestamp: bigint
  ] & {
    fromToken: string;
    toToken: string;
    amount: bigint;
    executor: string;
    timestamp: bigint;
  };
}

export interface TreasuryVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "TREASURER_ROLE"
      | "YIELD_MANAGER_ROLE"
      | "addReserve"
      | "addYieldProduct"
      | "approvalThreshold"
      | "depositToYieldProduct"
      | "getNativeBalance"
      | "getRebalanceHistory"
      | "getReserveCount"
      | "getRoleAdmin"
      | "getYieldProductCount"
      | "grantRole"
      | "hasApproved"
      | "hasRole"
      | "lastNAVUpdate"
      | "pendingApprovals"
      | "rebalance"
      | "rebalanceHistory"
      | "renounceRole"
      | "requiredApprovals"
      | "reserves"
      | "revokeRole"
      | "supportsInterface"
      | "totalTreasuryValueUSD"
      | "updateNAV"
      | "updateReserveTarget"
      | "updateYieldProduct"
      | "withdrawNative"
      | "withdrawToken"
      | "yieldProducts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApprovalSubmitted"
      | "DepositToYield"
      | "NAVUpdated"
      | "NativeDeposit"
      | "NativeWithdrawal"
      | "Rebalanced"
      | "ReserveAdded"
      | "ReserveUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "YieldProductAdded"
      | "YieldProductUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "YIELD_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addReserve",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addYieldProduct",
    values: [string, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvalThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToYieldProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNativeBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRebalanceHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldProductCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastNAVUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingApprovals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalance",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserves",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalTreasuryValueUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateNAV",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReserveTarget",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateYieldProduct",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldProducts",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "YIELD_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addReserve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addYieldProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvalThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToYieldProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNativeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRebalanceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldProductCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastNAVUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserves", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTreasuryValueUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateNAV", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateReserveTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateYieldProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldProducts",
    data: BytesLike
  ): Result;
}

export namespace ApprovalSubmittedEvent {
  export type InputTuple = [actionHash: BytesLike, approver: AddressLike];
  export type OutputTuple = [actionHash: string, approver: string];
  export interface OutputObject {
    actionHash: string;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositToYieldEvent {
  export type InputTuple = [
    productId: BigNumberish,
    amount: BigNumberish,
    depositor: AddressLike
  ];
  export type OutputTuple = [
    productId: bigint,
    amount: bigint,
    depositor: string
  ];
  export interface OutputObject {
    productId: bigint;
    amount: bigint;
    depositor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NAVUpdatedEvent {
  export type InputTuple = [newValue: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newValue: bigint, timestamp: bigint];
  export interface OutputObject {
    newValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeDepositEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeWithdrawalEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalancedEvent {
  export type InputTuple = [
    fromToken: AddressLike,
    toToken: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    fromToken: string,
    toToken: string,
    amount: bigint
  ];
  export interface OutputObject {
    fromToken: string;
    toToken: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveAddedEvent {
  export type InputTuple = [
    reserveId: BigNumberish,
    token: AddressLike,
    name: string,
    targetBps: BigNumberish
  ];
  export type OutputTuple = [
    reserveId: bigint,
    token: string,
    name: string,
    targetBps: bigint
  ];
  export interface OutputObject {
    reserveId: bigint;
    token: string;
    name: string;
    targetBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveUpdatedEvent {
  export type InputTuple = [
    reserveId: BigNumberish,
    newTargetBps: BigNumberish
  ];
  export type OutputTuple = [reserveId: bigint, newTargetBps: bigint];
  export interface OutputObject {
    reserveId: bigint;
    newTargetBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldProductAddedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    name: string,
    apyBps: BigNumberish
  ];
  export type OutputTuple = [productId: bigint, name: string, apyBps: bigint];
  export interface OutputObject {
    productId: bigint;
    name: string;
    apyBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldProductUpdatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    newApyBps: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    productId: bigint,
    newApyBps: bigint,
    active: boolean
  ];
  export interface OutputObject {
    productId: bigint;
    newApyBps: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryVault extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryVault;
  waitForDeployment(): Promise<this>;

  interface: TreasuryVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  TREASURER_ROLE: TypedContractMethod<[], [string], "view">;

  YIELD_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  addReserve: TypedContractMethod<
    [token_: AddressLike, name_: string, targetBps_: BigNumberish],
    [void],
    "nonpayable"
  >;

  addYieldProduct: TypedContractMethod<
    [
      name_: string,
      apyBps_: BigNumberish,
      riskLevel_: string,
      provider_: string,
      maturityDate_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  approvalThreshold: TypedContractMethod<[], [bigint], "view">;

  depositToYieldProduct: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "payable"
  >;

  getNativeBalance: TypedContractMethod<[], [bigint], "view">;

  getRebalanceHistory: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [TreasuryVault.RebalanceActionStructOutput[]],
    "view"
  >;

  getReserveCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getYieldProductCount: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasApproved: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lastNAVUpdate: TypedContractMethod<[], [bigint], "view">;

  pendingApprovals: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  rebalance: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rebalanceHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, bigint] & {
        fromToken: string;
        toToken: string;
        amount: bigint;
        executor: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  reserves: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        token: string;
        name: string;
        targetAllocationBps: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalTreasuryValueUSD: TypedContractMethod<[], [bigint], "view">;

  updateNAV: TypedContractMethod<
    [newValueUSD: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateReserveTarget: TypedContractMethod<
    [reserveId: BigNumberish, newTargetBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateYieldProduct: TypedContractMethod<
    [productId: BigNumberish, newApyBps: BigNumberish, active_: boolean],
    [void],
    "nonpayable"
  >;

  withdrawNative: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldProducts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint, boolean] & {
        name: string;
        apyBps: bigint;
        riskLevel: string;
        provider: string;
        totalDeposited: bigint;
        maturityDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TREASURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "YIELD_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addReserve"
  ): TypedContractMethod<
    [token_: AddressLike, name_: string, targetBps_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addYieldProduct"
  ): TypedContractMethod<
    [
      name_: string,
      apyBps_: BigNumberish,
      riskLevel_: string,
      provider_: string,
      maturityDate_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvalThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositToYieldProduct"
  ): TypedContractMethod<[productId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getNativeBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRebalanceHistory"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [TreasuryVault.RebalanceActionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getYieldProductCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastNAVUpdate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingApprovals"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rebalanceHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, bigint] & {
        fromToken: string;
        toToken: string;
        amount: bigint;
        executor: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserves"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        token: string;
        name: string;
        targetAllocationBps: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalTreasuryValueUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateNAV"
  ): TypedContractMethod<[newValueUSD: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReserveTarget"
  ): TypedContractMethod<
    [reserveId: BigNumberish, newTargetBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateYieldProduct"
  ): TypedContractMethod<
    [productId: BigNumberish, newApyBps: BigNumberish, active_: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawNative"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "yieldProducts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint, boolean] & {
        name: string;
        apyBps: bigint;
        riskLevel: string;
        provider: string;
        totalDeposited: bigint;
        maturityDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ApprovalSubmitted"
  ): TypedContractEvent<
    ApprovalSubmittedEvent.InputTuple,
    ApprovalSubmittedEvent.OutputTuple,
    ApprovalSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DepositToYield"
  ): TypedContractEvent<
    DepositToYieldEvent.InputTuple,
    DepositToYieldEvent.OutputTuple,
    DepositToYieldEvent.OutputObject
  >;
  getEvent(
    key: "NAVUpdated"
  ): TypedContractEvent<
    NAVUpdatedEvent.InputTuple,
    NAVUpdatedEvent.OutputTuple,
    NAVUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NativeDeposit"
  ): TypedContractEvent<
    NativeDepositEvent.InputTuple,
    NativeDepositEvent.OutputTuple,
    NativeDepositEvent.OutputObject
  >;
  getEvent(
    key: "NativeWithdrawal"
  ): TypedContractEvent<
    NativeWithdrawalEvent.InputTuple,
    NativeWithdrawalEvent.OutputTuple,
    NativeWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "Rebalanced"
  ): TypedContractEvent<
    RebalancedEvent.InputTuple,
    RebalancedEvent.OutputTuple,
    RebalancedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveAdded"
  ): TypedContractEvent<
    ReserveAddedEvent.InputTuple,
    ReserveAddedEvent.OutputTuple,
    ReserveAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveUpdated"
  ): TypedContractEvent<
    ReserveUpdatedEvent.InputTuple,
    ReserveUpdatedEvent.OutputTuple,
    ReserveUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "YieldProductAdded"
  ): TypedContractEvent<
    YieldProductAddedEvent.InputTuple,
    YieldProductAddedEvent.OutputTuple,
    YieldProductAddedEvent.OutputObject
  >;
  getEvent(
    key: "YieldProductUpdated"
  ): TypedContractEvent<
    YieldProductUpdatedEvent.InputTuple,
    YieldProductUpdatedEvent.OutputTuple,
    YieldProductUpdatedEvent.OutputObject
  >;

  filters: {
    "ApprovalSubmitted(bytes32,address)": TypedContractEvent<
      ApprovalSubmittedEvent.InputTuple,
      ApprovalSubmittedEvent.OutputTuple,
      ApprovalSubmittedEvent.OutputObject
    >;
    ApprovalSubmitted: TypedContractEvent<
      ApprovalSubmittedEvent.InputTuple,
      ApprovalSubmittedEvent.OutputTuple,
      ApprovalSubmittedEvent.OutputObject
    >;

    "DepositToYield(uint256,uint256,address)": TypedContractEvent<
      DepositToYieldEvent.InputTuple,
      DepositToYieldEvent.OutputTuple,
      DepositToYieldEvent.OutputObject
    >;
    DepositToYield: TypedContractEvent<
      DepositToYieldEvent.InputTuple,
      DepositToYieldEvent.OutputTuple,
      DepositToYieldEvent.OutputObject
    >;

    "NAVUpdated(uint256,uint256)": TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;
    NAVUpdated: TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;

    "NativeDeposit(address,uint256)": TypedContractEvent<
      NativeDepositEvent.InputTuple,
      NativeDepositEvent.OutputTuple,
      NativeDepositEvent.OutputObject
    >;
    NativeDeposit: TypedContractEvent<
      NativeDepositEvent.InputTuple,
      NativeDepositEvent.OutputTuple,
      NativeDepositEvent.OutputObject
    >;

    "NativeWithdrawal(address,uint256)": TypedContractEvent<
      NativeWithdrawalEvent.InputTuple,
      NativeWithdrawalEvent.OutputTuple,
      NativeWithdrawalEvent.OutputObject
    >;
    NativeWithdrawal: TypedContractEvent<
      NativeWithdrawalEvent.InputTuple,
      NativeWithdrawalEvent.OutputTuple,
      NativeWithdrawalEvent.OutputObject
    >;

    "Rebalanced(address,address,uint256)": TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;
    Rebalanced: TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;

    "ReserveAdded(uint256,address,string,uint256)": TypedContractEvent<
      ReserveAddedEvent.InputTuple,
      ReserveAddedEvent.OutputTuple,
      ReserveAddedEvent.OutputObject
    >;
    ReserveAdded: TypedContractEvent<
      ReserveAddedEvent.InputTuple,
      ReserveAddedEvent.OutputTuple,
      ReserveAddedEvent.OutputObject
    >;

    "ReserveUpdated(uint256,uint256)": TypedContractEvent<
      ReserveUpdatedEvent.InputTuple,
      ReserveUpdatedEvent.OutputTuple,
      ReserveUpdatedEvent.OutputObject
    >;
    ReserveUpdated: TypedContractEvent<
      ReserveUpdatedEvent.InputTuple,
      ReserveUpdatedEvent.OutputTuple,
      ReserveUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "YieldProductAdded(uint256,string,uint256)": TypedContractEvent<
      YieldProductAddedEvent.InputTuple,
      YieldProductAddedEvent.OutputTuple,
      YieldProductAddedEvent.OutputObject
    >;
    YieldProductAdded: TypedContractEvent<
      YieldProductAddedEvent.InputTuple,
      YieldProductAddedEvent.OutputTuple,
      YieldProductAddedEvent.OutputObject
    >;

    "YieldProductUpdated(uint256,uint256,bool)": TypedContractEvent<
      YieldProductUpdatedEvent.InputTuple,
      YieldProductUpdatedEvent.OutputTuple,
      YieldProductUpdatedEvent.OutputObject
    >;
    YieldProductUpdated: TypedContractEvent<
      YieldProductUpdatedEvent.InputTuple,
      YieldProductUpdatedEvent.OutputTuple,
      YieldProductUpdatedEvent.OutputObject
    >;
  };
}
