/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RWAToken__factory } from "./RWAToken__factory";
export { RWATokenFactory__factory } from "./RWATokenFactory__factory";
